config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'signup', to: 'user#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root "home#home", as: :home
  get "/home" => "home#home"
  get "/about" => "home#about", as: :about_us
  resources :posts do
    resources :comments, only: [:create, :edit, :destroy, :update]
    resources :likes, only: [:create, :destroy]
  end
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :users, only: [:new, :create, :edit, :update, :delete]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :body, presence: true

  def user_full_name
    user ? user.full_name : ""
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_and_authorize_comment, only: :destroy

  def create
    @post = Post.find params[:post_id]
    @comment = Comment.new comment_params
    @comment.user = current_user
    @comment.post = @post
    if @comment.save
      redirect_to post_path(@post), notice: 'Comment created successfully'
    else
      render "/posts/show"
    end
  end

  def edit
      @comment = Comment.find params[:id]
  end

  def destroy
    @comment.destroy
    redirect_to post_path(@post), notice: "Comment Deleted!"
  end

  def update
    @comment = Comment.find params[:id]
    if @comment.update comment_params
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  private

  def find_post
    @post = Post.find params[:post_id]
  end

  def comment_params
    params.require(:comment).permit(:body)
  end

  def find_and_authorize_comment
    @comment = @post.comments.find params[:id]
    redirect_to home_path unless can? :destroy, @comment
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments.html.erb
<% @post.comments.reverse_each do |comment| %>
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
    <% if comment.user_id %>
      By: <%= comment.user_full_name.titleize %>
      <% end %>
      <% if can? :edit, comment %>
        <%= link_to 'edit', edit_post_comment_path(@post, comment) %>
    <% end %>
      <% if can? :destroy, comment %>
        <%= link_to 'delete', post_comment_path(@post, comment), data: {confirm: "Are you sure?"}, method: :delete %>
    <% end %>
  </p>
<% end %>

<% if @comment.errors.any? %>
  <ul>
    <% @comment.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
  <% end %>

app/views/comments/_form.html.erb
<%= form_for([@post, @comment]) do |f| %>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/comments/edit.html.erb
<%= render "form" %>