config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'signup', to: 'user#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root "home#home", as: :home
  get "/home" => "home#home"
  get "/about" => "home#about", as: :about_us
  resources :posts do
    resources :comments, only: [:create, :edit, :destroy, :update]
    resources :likes, only: [:create, :destroy]
  end
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :users, only: [:new, :create, :edit, :update, :delete]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :users, through: :likes

  validates(:title, {presence: true, uniqueness: {message: "must be unique!"}})
  validates :body, presence: true
  def self.search(search)
    where("body ILIKE :search", search: "%#{search}%")
  end

  def user_full_name
    user ? user.full_name : ""
  end

  def like_for(user)
    likes.find_by_user_id user if user
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :find_post, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!, except: [:index, :show]

  def new
    @post = Post.new
  end

  def update
    if @post.update post_params
      # redirect_to post_path(@post)
      redirect_to root_path, alert: "access defined" unless can? :update, @post
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def create
    @post = Post.new post_params
    @post.user = current_user
    if @post.save
      redirect_to post_path(@post), notice: 'Post created successfully'
    else
      render :new
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path, alert: "access defined" unless can? :destroy, @post
  end

  def edit
    redirect_to root_path, alert: "access defined" unless can? :edit, @post
  end

  def index
    @posts = Post.all
    @post_total = Post.count
    if params[:search]
      @posts = Post.search(params[:search]).order("created_at DESC")
    else
      @posts = Post.all.order('created_at DESC')
    end
    @posts = @posts.page(params[:page]).per(10)
  end

  def show
    @comment = Comment.new
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def find_post
    @post = Post.find params[:id]
  end

  def find_owned_post
    @post = current_user.posts.find params[:id]
  end

  def like_for(user)
   likes.find_by_user_id user if user
  end

  def user_like
    @user_like ||= @post.like_for(current_user)
  end
  helper_method :user_like

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_for @post do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "form" %>

app/views/posts/index.html.erb
<h1>All Posts (<%= @post_total %>)</h1>
<%= form_tag(posts_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search Posts" %>
<%= submit_tag "Search" %>
<% end %>

<% if @posts.present? %>
  <%= render @posts %>
<% else %>
  <p>There are no posts containing the term(s) <%= params[:search] %>.</p>
<% end %>
<% @posts.each do |post| %>
<div>
  <h2><%= link_to post.title, post_path(post) %> (<%= post.comments.count %>)</h2>
  <p><%= post.body %></p>

  <hr>
</div>
<% end %>
<%= paginate @posts %>
<%= page_entries_info @posts %>

app/views/posts/new.html.erb
<h1>New Posts</h1>

<%= render "form" %>

app/views/posts/show.html.erb
<h1><%= @post.title %> <%= @post.likes ? @post.likes.count : '' %></h1>
  <!-- # (@post.likes.count > 1 ? "(#{@post.likes.count} likes)" : "(#{@post.likes.count} like)") : ""%></h1> -->

<p><%= @post.body %></p>

<p><%= @post.created_at %></p>

<h2>Comments</h2>
        <%= render "/comments/comments", comments: @post.comments %>


<h2>Add a comment:</h2>
        <%= render "/comments/form", comment: @comment %>

<% if can? :edit, @post %>
  <%= link_to "Edit", edit_post_path(@post) %>
<% end %>
<% if can? :destroy, @post %>
  <%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure"} %>
<% end %>
<% if user_like %>
  <%= link_to "Un-Like", post_like_path(@post, user_like), method: :delete %>
<% else %>
  <%= link_to "Like", post_likes_path(@post), method: :post %>
<% end %>

<p>Created By: <%= @post.user_full_name.titleize %></p>