config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'signup', to: 'user#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root "home#home", as: :home
  get "/home" => "home#home"
  get "/about" => "home#about", as: :about_us
  resources :posts do
    resources :comments, only: [:create, :edit, :destroy, :update]
    resources :likes, only: [:create, :destroy]
  end
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :users, only: [:new, :create, :edit, :update, :delete]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<style>
html {
    height: 100%;
    box-sizing: border-box;
}
body {
    min-height: 100%;
    position: relative;
    margin: 0;
    padding-bottom:195px;
}
ul {
    margin: 0;
    text-align: center;
    display: flex;
    list-style-type: none;
    background-color: #000;
    height: 70px;
    align-items: center;
    padding: 0 13em;
    justify-content: center;
}

li {
  padding: 0 20px;
  font-size: 25px;
  font-weight: 600;
}

li a, li {
    color: white;
    text-align: center;
    text-decoration: none;
}

li a:hover:not(.active) {
    background-color: #111;
}
.home-bg {
  width: 100%;
  height: 30em;
  object-fit: cover;
      object-position: 37% 59%;
}

</style>
  <body>
    <div class="row" style="border-bottom: 1px solid #2d2a2a;">
      <ul>
        <li style="ont-weight: 900;
        font-size: xx-large; font-weight: 600;    text-transform: uppercase;"><%= link_to "Alex Tang", home_path %></li>
        <li><%= link_to "Blog", posts_path %></li>
        <li><%= link_to "About", about_us_path %></li>
        <li><a href="#">Speak to me!</a></li>
        <li><a href="#">Hire me!</a></li>
      </ul>
    </div>






    <!-- <%= link_to "New Post", new_post_path %>

    <% if user_signed_in? %>
      Hello <%= link_to "#{current_user.first_name}", edit_user_path(current_user) %>,
      <%= link_to "Log out", logout_path %>
    <% else %>
      <%= link_to "Sign Up", signup_path %>
      <%= link_to "Sign In", login_path %>
    <% end %> -->
    <%= flash[:notice] || flash[:alert] %>
    <%= yield %>
  </body>
</html>